In [6]:
import pandas as pd

df = pd.read_csv("/home/prajwalmac/data_science_self/pandas_self/datasets/Pokemon.csv")
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [7]:
df = df.drop(columns='#')
df

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

### groupby()

In [8]:
type1_group = df.groupby('Type 1')
type1_group

In [9]:
len(type1_group)

18

In [10]:
type1_group.size().sort_values(ascending=False)

Type 1
Water       112
Normal       98
Grass        70
Bug          69
Psychic      57
Fire         52
Electric     44
Rock         44
Ground       32
Dragon       32
Ghost        32
Dark         31
Poison       28
Fighting     27
Steel        27
Ice          24
Fairy        17
Flying        4
dtype: int64

In [11]:
#return first pokemon from each type
type1_group.first()

,Name,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,,,
Bug,Caterpie,Flying,195,45,30,35,20,20,45,1,False
Dark,Umbreon,Flying,525,95,65,110,60,130,65,2,False
Dragon,Dratini,Flying,300,41,64,45,50,50,50,1,False
Electric,Pikachu,Steel,320,35,55,40,50,50,90,1,False
Fairy,Clefairy,Flying,323,70,45,48,60,65,35,1,False
Fighting,Mankey,Psychic,305,40,80,35,35,45,70,1,False
Fire,Charmander,Flying,309,39,52,43,60,50,65,1,False
Flying,TornadusIncarnate Forme,Dragon,580,79,115,70,125,80,111,5,True
Ghost,Gastly,Poison,310,30,35,30,100,35,80,1,False
Grass,Bulbasaur,Poison,318,45,49,49,65,65,45,1,False
Ground,Sandshrew,Rock,300,50,75,85,20,30,40,1,False
Ice,Jynx,Psychic,455,65,50,35,115,95,95,1,False
Normal,Pidgey,Flying,251,40,45,40,35,35,56,1,False
Poison,Ekans,Ground,288,35,60,44,40,54,55,1,False
Psychic,Abra,Fairy,310,25,20,15,105,55,90,1,False
Rock,Geodude,Ground,300,40,80,100,30,30,20,1,False
Steel,Steelix,Ground,510,75,85,200,55,65,30,2,False
Water,Squirtle,Fighting,314,44,48,65,50,64,43,1,False

In [12]:
#return first pokemon from each type
type1_group.last()

,Name,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,,,
Bug,Vivillon,Flying,411,80,52,50,90,50,89,6,False
Dark,Yveltal,Flying,680,126,131,95,131,98,99,6,True
Dragon,Zygarde50% Forme,Ground,600,108,100,121,81,95,95,6,True
Electric,Dedenne,Fairy,431,67,58,57,81,67,101,6,False
Fairy,Xerneas,Flying,680,126,131,95,131,98,99,6,True
Fighting,Hawlucha,Flying,500,78,92,75,74,63,118,6,False
Fire,Volcanion,Water,600,80,110,120,130,90,70,6,True
Flying,Noivern,Dragon,535,85,70,80,97,80,123,6,False
Ghost,GourgeistSuper Size,Grass,494,85,100,122,58,75,54,6,False
Grass,Gogoat,Fighting,531,123,100,62,97,81,68,6,False
Ground,LandorusTherian Forme,Flying,600,89,145,90,105,80,91,5,True
Ice,Avalugg,Ghost,514,95,117,184,44,46,28,6,False
Normal,Furfrou,Flying,472,75,80,60,65,90,102,6,False
Poison,Dragalge,Dragon,494,65,75,90,97,123,44,6,False
Psychic,HoopaHoopa Unbound,Dark,680,80,160,60,170,130,80,6,True
Rock,DiancieMega Diancie,Fairy,700,50,160,110,160,110,110,6,True
Steel,Klefki,Fairy,470,57,80,91,80,87,75,6,False
Water,Clawitzer,Dark,500,71,73,88,120,89,59,6,False

In [ ]:
legendary = df.groupby(df["Legendary"]==True)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x7f2805212330>

In [21]:
legendary

In [22]:
legendary.first()

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Legendary,,,,,,,,,,,,
False,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
True,Articuno,Ice,Flying,580,90,85,100,95,125,85,1,True

In [32]:
type1_group['Speed'].min().sort_values()

Type 1
Bug          5
Normal       5
Grass       10
Rock        10
Ground      10
Fairy       15
Water       15
Fire        20
Psychic     20
Ghost       20
Dark        20
Steel       23
Poison      25
Fighting    25
Ice         25
Electric    35
Dragon      40
Flying      55
Name: Speed, dtype: int64

In [30]:
type1_group['Attack'].max().sort_values(ascending=False)

Type 1
Psychic     190
Bug         185
Ground      180
Dragon      180
Rock        165
Ghost       165
Fire        160
Normal      160
Water       155
Dark        150
Steel       150
Fighting    145
Grass       132
Fairy       131
Ice         130
Electric    123
Flying      115
Poison      106
Name: Attack, dtype: int64

## Aggregation

In [13]:
df['Type 1'].unique()

array(['Grass', 'Fire', 'Water', 'Normal', 'Bug', 'Fairy', 'Fighting',
       'Psychic', 'Steel', 'Dark', 'Rock', 'Poison', 'Electric', 'Dragon',
       'Ghost', 'Ice', 'Flying'], dtype=object)

In [10]:
df['Type 1'].value_counts()

Type 1
Ghost       10
Rock         9
Fairy        9
Fire         7
Steel        5
Psychic      5
Water        5
Dragon       4
Normal       4
Grass        3
Bug          3
Fighting     3
Dark         3
Electric     3
Poison       2
Ice          2
Flying       2
Name: count, dtype: int64

In [18]:
## Finding mean of numeric data only from the dataframe

print(df.mean(numeric_only=True))
print("\n")
print(df.min(numeric_only=True))

Total         437.291139
HP             68.329114
Attack         75.620253
Defense        76.139241
Sp. Atk        74.898734
Sp. Def        75.544304
Speed          66.759494
Generation      5.936709
Legendary       0.101266
dtype: float64


Total           200
HP               38
Attack           22
Defense          33
Sp. Atk          27
Sp. Def          25
Speed            23
Generation        1
Legendary     False
dtype: object

## Pivot Table

In [37]:
import os
os.getcwd()

'/home/prajwalmac/data_science_self/pandas_self/notebooks'

In [39]:
sample = pd.read_csv('/home/prajwalmac/data_science_self/pandas_self/datasets/sample_data.csv')
sample

   ID   Name  Age Gender  Marks_Math  Marks_Science  Marks_English Result
0   1    Ram   21      M          78             82             75   Pass
1   2   Sita   22      F          85             88             80   Pass
2   3   Gita   20      F          69             72             70   Pass
3   4   Hari   23      M          90             91             85   Pass
4   5   Nita   21      F          74             79             73   Pass
5   6   Aman   24      M          88             87             82   Pass
6   7   Rita   22      F          81             84             78   Pass
7   8  Kiran   23      M          76             80             77   Pass

In [41]:
table = sample.pivot_table(index='Gender', columns='Marks_Math',values='Result',aggfunc=max)
table

/tmp/ipykernel_6898/3350249648.py:1: FutureWarning: The provided callable <built-in function max> is currently using DataFrameGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  table = sample.pivot_table(index='Gender', columns='Marks_Math',values='Result',aggfunc=max)

Marks_Math    69    74    76    78    81    85    88    90
Gender
F           Pass  Pass   NaN   NaN  Pass  Pass   NaN   NaN
M            NaN   NaN  Pass  Pass   NaN   NaN  Pass  Pass